version: '3.3'

services:
  mysql: 
    image: mysql:5.7
    volumes:
      - ./create_database.sql:/docker-entrypoint-initdb.d/create_database.sql
    env_file: ./env/mysql.env

  rabbitmq:
    image: rabbitmq:alpine
    ports:
      - "15692:15692"

  app-python:
    build:
      context: .
      dockerfile: Dockerfile-python
    image: app-python
    depends_on:
      - rabbitmq
    ports:
      - "8000:8000"
    env_file: ./env/python.env

  app-node:
    build:
      context: .
      dockerfile: Dockerfile-node
    image: app-node
    depends_on:
      - rabbitmq
      - mysql
    ports:
      - "3000:3000"
    env_file: ./env/node.env

  mysql-exporter:
    image: prom/mysqld-exporter
    command: 
     - --config.my-cnf=/cfg/.my.cnf
     - --mysqld.address=mysql:3306
    volumes:
      - "./env/my.cnf:/cfg/.my.cnf"
    ports:
      - 9104:9104
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    ports:
      - 8080:8080
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
